---
- name: add golang ppa
  apt_repository:
    repo: ppa:longsleep/golang-backports
    filename: golang
    mode: 0644
  register: add_golang_ppa_result
  until: add_golang_ppa_result is successful
  when: ansible_lsb.release is version('20.04','<')

- name: install golang package
  apt:
    name: golang-{{ lin_go_version }}

- name: set global golang environment
  blockinfile:
    path: /etc/profile.d/golang.sh
    block: |
        # shellcheck shell=sh
        GO_VERSION={{ lin_go_version }}
        export GOROOT=/usr/lib/go-$GO_VERSION
        if [ -n "${PATH##*${GOROOT}/bin}" ] && [ -n "${PATH##*${GOROOT}/bin:*}" ]; then
            export PATH=$PATH:$GOROOT/bin
        fi
    insertbefore: BOF
    create: true
    mode: 0644
...
